### ISSUE TITLE
Why don't you experiment VMF loss on Transformer?

### ISSUE THREAD

**Issue by HuihuiChyan** [Sachin19/seq2seq-con#10]
I think Transformer is more mainstreamed than RNNSearch even back in 2019, but why didn't you experiment on Transformer? Was there a negative result?

**Comment by Sachin19** [comment]
Hi,

Although this work was presented in ICLR 2019, I actually did the work in 2017 and early 2018 when transformers weren't as widely adopted as they are now. Nevertheless, we redid all the experiments using transformers and obtained consistent results as reported in the paper. You can find the code in this repo on the branch called [onmt-transformers](https://github.com/Sachin19/seq2seq-con/tree/onmt-transformers/OpenNMT-py). We are planning to merge with master soon! 

Hope this helps.
