### ISSUE TITLE
Hyper-parameters to train word2vec/FastText

### ISSUE THREAD

**Issue by toshohirasawa** [Sachin19/seq2seq-con#11]
This question is a bit off-topic, but I would like to know what hyper-parameters you used to train word2vec/FastText models.

You have mentioned, "which were trained using the hyper-parameters recommended by the authors" in your paper, but not all kinds of parameters have been recommended in the authors' paper. 
If I may, I would like you to provide any scripts/codes to train embedding models.

Thanks!

**Comment by Sachin19** [comment]
Hi,

By recommended hyperpameteres, we meant the default parameters on word2vec and fasttext using skipgram objective.

For fasttext, we used this command:

`./fasttext skipgram -input <tokenized_corpus_file> -output <output_path> -dim 300 -thread 20`
