### ISSUE TITLE
How to use evaluate.sh?

### ISSUE THREAD

**Issue by jianqiaol** [Sachin19/seq2seq-con#3]
Hi,
Thanks for sharing the code. I was able to follow the instruction to train and decode. But it seems that the evaluate.sh takes a few inputs which were not specified. Could you give an working example for evaluate.sh please? Thank you!

**Comment by Sachin19** [comment]
Hi,

You need to use [moses](https://github.com/moses-smt/mosesdecoder) to be able to run evaluate.sh which detruecases and detokenizes the predicted translation file. Before running, set the path to mosesdecoder in the first line of evaluate.sh

To run evaluate.sh, you need three command line arguments:

1. Predicted file
2. Reference file (in the original format, which is not preprocessed in any way)
3. Language code of the target (en, fr, de etc)

Please let me know if you face any other issue,

Thanks.
Sachin

**Comment by jianqiaol** [comment]
Thanks a lot! I think it works. I got output like this:
Language: en
BLEU = 17.00, 51.1/25.9/14.4/8.1 (BP=0.856, ratio=0.866, hyp_len=39513, ref_len=45653)
