### ISSUE TITLE
function returns nothing

### ISSUE THREAD

**Issue by serjtroshin** [Sachin19/seq2seq-con#4]
https://github.com/Sachin19/seq2seq-con/blob/00e21254f4d7a23dfc0ce157a88c2eb8c5fdf47a/onmt/Beam.py#L112

**Comment by Sachin19** [comment]
Thanks for pointing this out! I have fixed it.

**Comment by serjtroshin** [comment]
Thanks! Also [here](https://github.com/Sachin19/seq2seq-con/blob/a4f3cd76fe86448c1918d33a90863aecbf1a2086/onmt/Translator.py#L350) you iterate over n_best hypotheses. But since [you want](https://github.com/Sachin19/seq2seq-con/blob/a4f3cd76fe86448c1918d33a90863aecbf1a2086/onmt/Beam.py#L112) to kill beam when eos is in the top hypothesis, you might end up killing beam when less than n_best hypotheses are finalized. This will raise an error [here](https://github.com/Sachin19/seq2seq-con/blob/a4f3cd76fe86448c1918d33a90863aecbf1a2086/onmt/Translator.py#L351) and [here](https://github.com/Sachin19/seq2seq-con/blob/a4f3cd76fe86448c1918d33a90863aecbf1a2086/translate.py#L134) since predScore[b] is in fact not always of the n_best size.

**Comment by Sachin19** [comment]
Thank you for reporting this! As has been mentioned in the paper, this code is adapted from open-nmt (with some code remnants for beam search) but we don't report beam search results. And the issues you report only appear when you try to do beam search and print multiple-hypothesis the code for which can be buggy as you pointed out. I intend to work on beam search and fix this in the future. For now I recommend that you use n_best=1 for correct behavior.
